[phases.setup]
aptPkgs = ["...", "apt-utils", "libcairo2-dev", "libjpeg8-dev", "libpango1.0-dev", "libgif-dev", "build-essential", "g++", "xvfb", "libgles2-mesa-dev", "libgbm-dev", "libxxf86vm-dev", "python3", "python3-pip"]
nixPkgs = ["...", "libuuid", "libglvnd"]
nixLibs = ["libuuid", "libglvnd"]

[phases.install]
paths = ["...", "/usr/local/bin"]
cmds = ["source ./setup.sh", "pip3 install gdown"]

[start]
cmd = "source ./run.sh"