[phases.setup]
aptPkgs = ["...", "apt-utils", "libcairo2-dev", "libjpeg8-dev", "libpango1.0-dev", "libgif-dev", "build-essential", "g++", "xvfb", "libgles2-mesa-dev", "libgbm-dev", "libxxf86vm-dev", "python3", "python3-pip"]
nixPkgs = ["...", "libuuid", "libglvnd", "curl"]
nixLibs = ["...", "libuuid", "libglvnd", "curl"]

[phases.install]
paths = ["...", "/usr/local/bin", "/usr/lib/x86_64-linux-gnu"]
cmds = ["source ./setup.sh", "pip3 install gdown", "npm i tileserver-gl@4.3.3"]

[start]
cmd = "source ./run.sh"